project:
  type: website
  output-dir: docs

website:
  title: "Gapminder Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: life-gdp.qmd
        text: Life Expectancy and GDP
      - href: life-population.qmd
        text: Life Expectancy and Population
      - href: country.qmd
        text: Country Analysis

format:
  html:
    theme: lumen
